runtime: nodejs10
service: default

env_variables:
  REACT_APP_BACKEND_URL: https://api.kavok.fr

handlers:
  - url: /static
    static_files: build/static/\1
    upload: build/static/.*\.(css|json|ico|js|jpg|png)$

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
