runtime: nodejs12
service: default

handlers:
  - url: /static
    static_dir: static
    secure: always
    redirect_http_response_code: 301

  - url: /(.*\.(json|ico|js))$
    static_files: \1
    upload: .*\.(json|ico|js)$
    secure: always
    redirect_http_response_code: 301

  - url: /.*
    static_files: index.html
    upload: index.html
    secure: always
    redirect_http_response_code: 301
