runtime: custom
env: flex
service: backend

beta_settings:
    cloud_sql_instances: theodercafe:europe-west2:theodercafe=tcp:5432

manual_scaling:
    instances: 1

env_variables:
    NODE_ENV: production
    TYPEORM_URL: postgres://the:cafe@172.17.0.1:5432/theodercafe
    TYPEORM_LOGGING: 'false'
    TYPEORM_ENTITIES: dist/**/*.entity.js,dist/src/**/*.entity.js
    TYPEORM_MIGRATIONS: dist/migration/*.js
    TYPEORM_MIGRATIONS_DIR: migration
    TYPEORM_USERNAME: the
    TYPEORM_PASSWORD: cafe
    TYPEORM_DATABASE: theodercafe
    TYPEORM_PORT: 5432
    FRONT_BASE_URL: https://theodercafe.com
    BACKEND_URL: https://api.theodercafe.com
    AUTH2_CLIENT_ID: google_auth2_id
    CLIENT_SECRET: google_client_secret
    JWT_SECRET_KEY: secret_key
    FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY: firebase_private_key
