---
- hosts: all
  gather_facts: False

  tasks:
    - name: Ansible check directory exists example.
      stat:
        path: theodercafe
      register: project_folder

    - name: Clone project
      raw: "git clone https://github.com/victorbrun/theodercafe.git"
      when: not project_folder.stat.exists

    - name: Pull project
      raw: "cd theodercafe && git fetch && git reset --hard origin/master"

    - name: Restart backend
      raw: "cd theodercafe/backend && npm install && npm run build && npm run migration:run && pm2 restart main"

    - name: Build frontend
      raw: "cd theodercafe/frontend && npm install && npm run build"

    - name: Copy final build in the served folder
      raw: "cp -r theodercafe/frontend/build/. theodercafe/frontend/build-prod"
